<?xml version="1.0" encoding="UTF-8" ?>
<!-- 外部约束-->
<!--<!DOCTYPE students SYSTEM "student.dtd">-->

<!-- 内部约束 -->
<!DOCTYPE students[
		<!ELEMENT students (student*) >
		<!ELEMENT student (name,age,sex)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT sex (#PCDATA)>
		<!ATTLIST student number ID #REQUIRED>
		]>
<students>
    <student number="s001">
        <name>张三</name>
        <age>23</age>
        <sex>male</sex>
    </student>

    <student number="s002">
        <name>李四</name>
        <age>20</age>
        <sex>female</sex>
    </student>
</students>